version: '3.8'

services:
  invert-app-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_APP_NODE_ENV=development
      - VITE_APP_BASE_API_URL=http://localhost:3000
